- name: apt upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: determine fish location
  command: which fish
  register: fish
- name: update fisher
  shell: "fisher update"
  args:
    executable: "{{ fish.stdout }}"
- name: update tldr
  shell: "tldr --update"
