- name: add repo
  ansible.builtin.apt_repository:
    repo: 'ppa:fish-shell/release-3'
    state: present
  become: true
- name: install packages
  ansible.builtin.apt: 
    name: fish
    state: present
    update_cache: true
  become: true
- name: determine install location
  command: which fish
  register: fish
- name: set default shell
  become: true
  user: 
    name: "{{ ansible_user_id }}"
    shell: "{{ fish.stdout }}"
- name: check if fisher is installed
  stat:
    path: "/home/{{ ansible_user_id }}/.config/fish/functions/fisher.fish"
  register: fisher_installed
- name: install fisher
  shell: "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  args:
    executable: "{{ fish.stdout }}"
  when: not fisher_installed.stat.exists
- name: copy config
  ansible.builtin.copy:
    src: ./
    dest: "/home/{{ ansible_user_id }}/.config/fish/"
    mode: preserve
- name: update fisher
  shell: "fisher update"
  args:
    executable: "{{ fish.stdout }}"
- name: init theme
  shell: "tide configure --auto --style=Rainbow --prompt_colors='True color' --show_time='24-hour format' --rainbow_prompt_separators=Round --powerline_prompt_heads=Round --powerline_prompt_tails=Round --powerline_prompt_style='Two lines, character and frame' --prompt_connection=Disconnected --powerline_right_prompt_frame=Yes --prompt_connection_andor_frame_color=Dark --prompt_spacing=Sparse --icons='Many icons' --transient=Yes"
  args:
    executable: "{{ fish.stdout }}"
